// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3jgoviUur2Vl-QhF17XapdquBms-GamE',
    appId: '1:1085939915040:web:818f5d94bf04924139df45',
    messagingSenderId: '1085939915040',
    projectId: 'first-proj-24d5d',
    authDomain: 'first-proj-24d5d.firebaseapp.com',
    databaseURL: 'https://first-proj-24d5d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-proj-24d5d.appspot.com',
    measurementId: 'G-JDBWJEPK0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2Fc7b4JGKOrARVLoso1CelsNj7Ep3jqI',
    appId: '1:54168995549:android:3968f9a3c3b8fd8253fd34',
    messagingSenderId: '54168995549',
    projectId: 'smart-bin-1cf13',
    databaseURL: 'https://smart-bin-1cf13-default-rtdb.firebaseio.com',
    storageBucket: 'smart-bin-1cf13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfVEBKsLnbzDEbjf406M1zdumCZN-HaHQ',
    appId: '1:1085939915040:ios:6b63c6839fc0698e39df45',
    messagingSenderId: '1085939915040',
    projectId: 'first-proj-24d5d',
    databaseURL: 'https://first-proj-24d5d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-proj-24d5d.appspot.com',
    iosBundleId: 'com.example.flutterHackathon1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfVEBKsLnbzDEbjf406M1zdumCZN-HaHQ',
    appId: '1:1085939915040:ios:2f01891fac72c7f839df45',
    messagingSenderId: '1085939915040',
    projectId: 'first-proj-24d5d',
    databaseURL: 'https://first-proj-24d5d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-proj-24d5d.appspot.com',
    iosBundleId: 'com.example.flutterHackathon1.RunnerTests',
  );
}